### ISSUE TITLE
configure_lib.sh won't work with gurobi

### ISSUE THREAD

**Issue by jithin-k-sreedharan** [krzysztof-turowski/duplication-divergence#40]
The configure_lib.sh file is not working with gurobi option in mac and linux. See the compiler flags set in Makefile of algorithms_puv branch

**Comment by jithin-k-sreedharan** [comment]
In Linux, I have to add the following lines manually:
export GUROBI_HOME="$HOME/gurobi801/linux64"
export PATH="${PATH}:${GUROBI_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
export GRB_LICENSE_FILE="$HOME/gurobi.lic"

**Comment by jithin-k-sreedharan** [comment]
It seems like the "find" command is not working

**Comment by krzysztof-turowski** [comment]
Corrected with the last push. Anyway, setting GRB_LICENSE_FILE from the script should be correct even before.
