### ISSUE TITLE
Beginning comment of source files

### ISSUE THREAD

**Issue by jithin-k-sreedharan** [krzysztof-turowski/duplication-divergence#50]
Almost all the source files have a comment for real-data, but wrong arguments. "p", "r" etc.
This is mostly applicable for parameter estimation source codes (I think I have corrected them, check it)

**Comment by krzysztof-turowski** [comment]
I'm pretty sure there are no more issues like that, thanks.

**Comment by jithin-k-sreedharan** [comment]
What I actually meant is the following (as mentioned in the email communication):
"I mentioned that all the usages of source files are clearly explained at the beginning of the file. I have already edited beginning comments of two files: “dd_automorphims.cpp”, “dd_ml_estimation.cpp”.
Please add such comments to all other source files like the above two files  as soon as possible"
We need to add complete syntax and output on the lines of what I have added in dd_automorphims.cpp”, “dd_ml_estimation.cpp. 

Please note that even though I have used the source files many times, it took sometime for me to figure out all the necessary and  optional running options. So this would be very confusing and demanding for a new person.
